#define PERMISSIVE_HOLD
// #define CHORDAL_HOLD

#define FLOW_TAP_TERM 200
#define TAPPING_TERM 200

// #define COMBO_TERM 20

// #define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#define ONESHOT_TIMEOUT 1000

// #define RGBLIGHT_SPLIT
// #define SPLIT_TRANSPORT_MIRROR
// #define SPLIT_LAYER_STATE_ENABLE
