#define SPLIT_LAYER_STATE_ENABLE
// #define SPLIT_TRANSPORT_MIRROR
// #define SPLIT_MODS_ENABLE
// #define RGBLIGHT_SPLIT
// #define MASTER_LEFT

#define PERMISSIVE_HOLD
// #define CHORDAL_HOLD

// #define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_CYCLE_LEFT_RIGHT
